account_name = 'mp'

import config_common as common_config

base_file_location = common_config.base_folder + account_name + '\\'
common_file_location = common_config.common_folder

FILE_LOCATION = {
    'str_file_location' : base_file_location + 'MP Search term report 08012019 to 09272019.xlsx',
    'target_file_location': base_file_location + 'MP Targeting report 08012019 to 09272019.xlsx',
    'bulk_file_location': base_file_location + 'MP BULk 30days.xlsx',
    'gen_lb_keywords_asins': base_file_location + account_name + '_gen_lb_keywords_asins.xlsx',
    #'keywords_to_add_file': base_file_location + account_name + '_keywords_to_add_file.xlsx',
    'keywords_to_add_file': base_file_location + 'new_product_keywords_to_add_file.xlsx',
    'sb_keywords_to_add_file': base_file_location + 'mp_ams_data.xlsx',
    'asins_to_add_file': base_file_location + account_name + '_asins_to_add_file.xlsx',
    #'asins_to_add_file': base_file_location + 'mp_asins_to_add.xlsx',
    'upload_file_location' : base_file_location + 'upload\\',
    'white_list_file': common_file_location + 'white_list_file.xlsx',
    'sku_names': common_file_location + 'SKU names and Kws.xlsx',
    'low_bid_keywords_asins': common_file_location + 'low_performing_keywords_asins.xlsx',
}

override_start_date = False
start_date = '04/26/2019'

override_end_date = False
end_date = '05/26/2019'

max_bid_limit_set = True
max_bid = 1.53
enhance_bid_multiplier = 1.0
max_highest_bid = 2.98
target_acos = 15
wl_target_acos = 65
bad_keyword_max_bid = 0.51
sales_optimized = True

PRODUCTS = [
{'search_name': 'FCO', 'sku': '6L-S5IM-ZW9C', 'ad_group_level': True},
{'search_name': 'Lavender Oil', 'sku': 'MY-ETEY-F5KK', 'ad_group_level': True},
{'search_name': 'NewPeppermintOil', 'sku': 'NewPeppermintOil', 'ad_group_level': True},
{'search_name': 'NewLemonOil', 'sku': 'NewLemonOil', 'ad_group_level': True},
{'search_name': 'Hot Cream', 'sku': 'PG-E0CL-C36F', 'ad_group_level': True},
{'search_name': 'HimalayanScrub', 'sku': 'HimalayanScrub', 'ad_group_level': True},
{'search_name': 'Eucalyptus Oil', 'sku': '6S-20QI-97SZ', 'ad_group_level': True},
{'search_name': 'Orange Oil', 'sku': 'D0-OKC7-SPUR', 'ad_group_level': True},
{'search_name': 'Lemongrass Oil', 'sku': 'RO-F5ZA-KSK2', 'ad_group_level': True},
{'search_name': 'GoldMask8.8oz', 'sku': 'GoldMask8.8oz', 'ad_group_level': True},
{'search_name': 'SetOf8EssentialOils', 'sku': 'SetOf8EssentialOils', 'ad_group_level': True},
{'search_name': 'TeaTreeBodyWash', 'sku': 'TeaTreeBodyWash', 'ad_group_level': True},
{'search_name': 'Bergamot Oil', 'sku': 'MajesticPureBergamotEssentialOil1oz', 'ad_group_level': True},
{'search_name': 'SoreMuscleMassageOil', 'sku': 'SoreMuscleMassageOil', 'ad_group_level': True},
{'search_name': 'Rosehip Oil', 'sku': 'AJ-CD9K-SAOC', 'ad_group_level': True},
{'search_name': 'Almond Oil', 'sku': '4U-0YX3-7HM3', 'ad_group_level': True},
{'search_name': 'Argan oil', 'sku': 'UT-X84W-ZTPT', 'ad_group_level': True},
{'search_name': 'RoseOil1oz', 'sku': 'RoseOil1oz', 'ad_group_level': True},
{'search_name': 'Aloe Vera Gel', 'sku': 'VP-F7D3-KUOM', 'ad_group_level': True},
{'search_name': 'TeaTreeOil4floz', 'sku': 'TeaTreeOil4floz', 'ad_group_level': True},
{'search_name': 'RosemaryOil-4oz', 'sku': 'RosemaryOil-4oz', 'ad_group_level': True},
{'search_name': 'JasmineOil4oz', 'sku': 'JasmineOil4oz', 'ad_group_level': True},
{'search_name': 'CelluliteOil8oz', 'sku': 'CelluliteOil8oz', 'ad_group_level': True},
{'search_name': 'Cedarwood Oil', 'sku': 'NwePureCedarwoodEssentialOil', 'ad_group_level': True},
{'search_name': 'YlangYlangOil4OZ', 'sku': 'YlangYlangOil4OZ', 'ad_group_level': True},
{'search_name': 'Castor Oil Eyelash', 'sku': 'OS-ODUT-24VL', 'ad_group_level': True},
{'search_name': 'Hair loss Shampoo', 'sku': 'KO-M9OF-WEJA', 'ad_group_level': True},
{'search_name': 'Grapeseed Oil', 'sku': '38-P4UU-LZHL', 'ad_group_level': True},
{'search_name': 'Biotin Shampoo', 'sku': 'DZ-1050-B3IR', 'ad_group_level': True},
{'search_name': 'Dead Sea Mud Mask', 'sku': '9D-BZC2-93AO', 'ad_group_level': True},
{'search_name': 'Grapefruit Oil', 'sku': '4J-YNLD-KLGK', 'ad_group_level': True},
{'search_name': 'BrownSugarScrub10oz', 'sku': 'BrownSugarScrub10oz', 'ad_group_level': True},
{'search_name': 'SweetOrangeScrub', 'sku': 'SweetOrangeScrub', 'ad_group_level': True},
{'search_name': 'ChamomileOil4oz', 'sku': 'ChamomileOil4oz', 'ad_group_level': True},
{'search_name': 'Myrrh Oil', 'sku': 'KO-I58S-WEWY', 'ad_group_level': True},
{'search_name': 'Oregano Oil', 'sku': 'E8-NMQ5-FJ05', 'ad_group_level': True},
{'search_name': 'Diffuser 250ml', 'sku': 'AdvanceOilDiffuser', 'ad_group_level': True},
{'search_name': 'CinnamonOil-4flOz', 'sku': 'CinnamonOil-4flOz', 'ad_group_level': True},
{'search_name': 'Aloe Vera Combo', 'sku': 'AloeVeraGel-16floz', 'ad_group_level': True},
{'search_name': 'CallusRemoverGel', 'sku': 'CallusRemoverGel', 'ad_group_level': True},
{'search_name': 'Frankincense4oz', 'sku': 'Frankincense4oz', 'ad_group_level': True},
{'search_name': 'HairGel16flOz', 'sku': 'HairGel16flOz', 'ad_group_level': True},
{'search_name': 'Clary Sage oil', 'sku': '7W-UX75-3750', 'ad_group_level': True},
{'search_name': 'GingerOil4FlOz', 'sku': 'GingerOil4FlOz', 'ad_group_level': True},
{'search_name': 'CloveOil-4flOz', 'sku': 'CloveOil-4flOz', 'ad_group_level': True},
{'search_name': 'Juniper Oil', 'sku': 'G9-CLOG-DZRL', 'ad_group_level': True},
{'search_name': 'Diffuser 400ml', 'sku': '500mLdiffuser', 'ad_group_level': True},
{'search_name': 'MatchaGreenTeaScrub', 'sku': 'MatchaGreenTeaScrub', 'ad_group_level': True},
{'search_name': 'NEWArganSetShampooConditioner', 'sku': 'NEWArganSetShampooConditioner', 'ad_group_level': True},
{'search_name': 'Tea trea wash seaweed', 'sku': 'TeaTreaBodyWash', 'ad_group_level': True},
{'search_name': 'ArabicaScrub10oz', 'sku': 'ArabicaScrub10oz', 'ad_group_level': True},
{'search_name': 'ShampooConditionerTeaTreeSet', 'sku': 'ShampooConditionerTeaTreeSet', 'ad_group_level': True},
{'search_name': 'Drying Lotion', 'sku': 'P8-ISVD-I4CL', 'ad_group_level': True},
{'search_name': 'Bentonite Clay', 'sku': 'BX-N0NF-ETC9', 'ad_group_level': True},
{'search_name': 'Castor Oil', 'sku': 'LV-XBR2-FJDV', 'ad_group_level': True},
{'search_name': 'ArganConditioner16flOz', 'sku': 'ArganConditioner16flOz', 'ad_group_level': True},
{'search_name': 'SandalwoodOil-1flOz', 'sku': 'SandalwoodOil-1flOz', 'ad_group_level': True},
{'search_name': 'NewGeraniumOil2oz', 'sku': 'NewGeraniumOil2oz', 'ad_group_level': True},
{'search_name': 'NailPolishRemover4floz', 'sku': 'NailPolishRemover4floz', 'ad_group_level': True},
{'search_name': 'AcaiBerryScrub', 'sku': 'AcaiBerryScrub', 'ad_group_level': True},
{'search_name': 'NewWatermelonScrub', 'sku': 'NewWatermelon', 'ad_group_level': True},
{'search_name': 'NailFungusTreatment', 'sku': 'NailFungusTreatment', 'ad_group_level': True},
{'search_name': 'Himalayan-Coffee-Scrubs', 'sku': 'Himalayan-Coffee-Scrubs', 'ad_group_level': True},
{'search_name': 'LotionVitaminC', 'sku': 'LotionVitaminC', 'ad_group_level': True},
{'search_name': 'Coconut Hair Mask', 'sku': 'KV-R48F-ZRVY', 'ad_group_level': True},
{'search_name': 'essential oil blends', 'sku': 'FL-PF4H-2VT8', 'ad_group_level': True},
{'search_name': 'Rosemary shampoo', 'sku': '97-IG90-MOAA', 'ad_group_level': True},
{'search_name': 'Himalayan Salt lamp', 'sku': 'B0-XL4G-CGTE', 'ad_group_level': True},
{'search_name': 'TeethWhiteningCharcoal', 'sku': 'TeethWhiteningCharcoal', 'ad_group_level': True},
{'search_name': 'Eyelash Serum 5ml', 'sku': 'EyelashSerum3.5ml', 'ad_group_level': True},
{'search_name': 'Daily Moisturizer', 'sku': 'WonderLotion-9Oz', 'ad_group_level': True},
{'search_name': 'AfterShaveBalm-4floz', 'sku': 'AfterShaveBalm-4floz', 'ad_group_level': True},
{'search_name': 'Jojoba Oil', 'sku': 'JB-RO97-9L06', 'ad_group_level': True},
{'search_name': 'Black Pepper', 'sku': '48-62AK-XNDW', 'ad_group_level': True},
{'search_name': 'TripleActionEyeCream1FL', 'sku': 'TripleActionEyeCream1FL', 'ad_group_level': True},
{'search_name': 'VitaminC-Serum 1floz', 'sku': 'VitaminC-Serum 1floz', 'ad_group_level': True},
{'search_name': 'ShavingCream-4flOz', 'sku': 'ShavingCream-4flOz', 'ad_group_level': True},
{'search_name': 'SuperRetinolSerum1oz', 'sku': 'SuperRetinolSerum1oz', 'ad_group_level': True},
{'search_name': 'HairGel-8floz', 'sku': 'HairGel-8floz', 'ad_group_level': True},
{'search_name': 'Frankincense Oil', 'sku': '1Z-OI9H-EH61', 'ad_group_level': True},
{'search_name': 'Shaving Kit', 'sku': 'GC-BZDF-8KT9', 'ad_group_level': True},
{'search_name': 'BrighteningSerum1FL', 'sku': 'BrighteningSerum1FL', 'ad_group_level': True},
{'search_name': 'Blue Eye Gel', 'sku': 'H0-S1BK-33MJ', 'ad_group_level': True},
{'search_name': 'RetinalEyeCream-1flOz', 'sku': 'RetinalEyeCream-1flOz', 'ad_group_level': True},
{'search_name': 'RetinolCream1oz', 'sku': 'RetinolCream1oz', 'ad_group_level': True},
{'search_name': 'FacialCleanserCharcoal4flOz', 'sku': 'FacialCleanserCharcoal4flOz', 'ad_group_level': True},
{'search_name': 'CamelliaCleansingOil-9flOz', 'sku': 'CamelliaCleansingOil-9flOz', 'ad_group_level': True},
{'search_name': 'SetOf6EssentialOils', 'sku': 'SetOf6EssentialOils', 'ad_group_level': True},
{'search_name': 'RosehipCreamCleanser', 'sku': 'RosehipCreamCleanser', 'ad_group_level': True},
{'search_name': 'TeaTreeBodyFootScrub', 'sku': 'TeaTreeBodyFootScrub', 'ad_group_level': True},
{'search_name': 'Essential oil set of 6', 'sku': 'Set6OilsAromatherapy', 'ad_group_level': True},
{'search_name': 'Dead Sea TTO', 'sku': 'DeadSeaMudMaskTTO', 'ad_group_level': True},
{'search_name': 'BathBombs6', 'sku': 'BathBombs6', 'ad_group_level': True},
{'search_name': 'Helichrysum oil', 'sku': 'Helichrysumoil1oz', 'ad_group_level': True},
{'search_name': 'ArganOilHairMask', 'sku': 'ArganOilHairMask', 'ad_group_level': True},
{'search_name': 'DeadSeaSaltScrub', 'sku': 'DeadSeaSaltScrub', 'ad_group_level': True},
{'search_name': 'LavenderMassageOil', 'sku': 'LavenderMassageOil', 'ad_group_level': True},
{'search_name': 'EGFScarSerum', 'sku': 'EGFScarSerum', 'ad_group_level': True},
{'search_name': 'Callus remover 16 oz', 'sku': 'CallusRemoverTwin', 'ad_group_level': True},
{'search_name': 'TeaTreeShampoo16floz', 'sku': 'TeaTreeShampoo16floz', 'ad_group_level': True},
{'search_name': 'Shea butter shampoo conditioner', 'sku': 'SheaButterShamppo+Conditioner', 'ad_group_level': True},
{'search_name': 'LavenderCleansingOil', 'sku': 'LavenderCleansingOil', 'ad_group_level': True},
{'search_name': 'Cellulite Body Scrub', 'sku': 'CelluliteBodyScrubWLemon', 'ad_group_level': True},
{'search_name': 'Cooling Massage Cream', 'sku': 'CoolingMuscleCream', 'ad_group_level': True},
{'search_name': 'DSMM with Lavender', 'sku': 'DeadSeaMudMaskLavender', 'ad_group_level': True},
]
##[
##    {
##    'identification' : 'FCO', # Sheets in excel will read and write with this name
##    'search_name' : 'FCO', # Search identifier in Campaign or Ad group
##    'sku' : '6L-S5IM-ZW9C',
##    'ad_group_level' : True, # Filtering will be applied on Ad Group (not campaign)
##    },
##    {
##    'identification' : 'Lavender Oil',
##    'search_name' : 'Lavender Oil',
##    'sku' : 'MY-ETEY-F5KK',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'NewPeppermintOil',
##    'search_name' : 'NewPeppermintOil',
##    'sku' : 'NewPeppermintOil',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'NewLemonOil',
##    'search_name' : 'NewLemonOil',
##    'sku' : 'NewLemonOil',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Hot Cream',
##    'search_name' : 'Hot Cream',
##    'sku' : 'PG-E0CL-C36F',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'HimalayanScrub',
##    'search_name' : 'HimalayanScrub',
##    'sku' : 'HimalayanScrub',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'GoldMask8.8oz',
##    'search_name' : 'GoldMask8.8oz',
##    'sku' : 'GoldMask8.8oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'SetOf8EssentialOils',
##    'search_name' : 'SetOf8EssentialOils',
##    'sku' : 'SetOf8EssentialOils',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'SoreMuscleMassageOil',
##    'search_name' : 'SoreMuscleMassageOil',
##    'sku' : 'SoreMuscleMassageOil',
##    'ad_group_level' : True,
##    },
##    #written by raza
##    {
##    'identification' : 'Rosehip Oil',
##    'search_name' : 'Rosehip Oil',
##    'sku' : 'AJ-CD9K-SAOC',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Almond Oil',
##    'search_name' : 'Almond Oil',
##    'sku' : '4U-0YX3-7HM3',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Argan oil',
##    'search_name' : 'Argan oil',
##    'sku' : 'UT-X84W-ZTPT',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'RoseOil1oz',
##    'search_name' : 'RoseOil1oz',
##    'sku' : 'RoseOil1oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Aloe Vera Gel',
##    'search_name' : 'Aloe Vera Gel',
##    'sku' : 'VP-F7D3-KUOM',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'TeaTreeOil4floz',
##    'search_name' : 'TeaTreeOil4floz',
##    'sku' : 'TeaTreeOil4floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'RosemaryOil-4oz',
##    'search_name' : 'RosemaryOil-4oz',
##    'sku' : 'RosemaryOil-4oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'JasmineOil4oz',
##    'search_name' : 'JasmineOil4oz',
##    'sku' : 'JasmineOil4oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'CelluliteOil8oz',
##    'search_name' : 'CelluliteOil8oz',
##    'sku' : 'CelluliteOil8oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Castor Oil Eyelash',
##    'search_name' : 'Castor Oil Eyelash',
##    'sku' : 'OS-ODUT-24VL',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Hair loss Shampoo',
##    'search_name' : 'Hair loss Shampoo',
##    'sku' : 'KO-M9OF-WEJA',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Grapeseed Oil',
##    'search_name' : 'Grapeseed Oil',
##    'sku' : '38-P4UU-LZHL',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Biotin Shampoo',
##    'search_name' : 'Biotin Shampoo',
##    'sku' : 'DZ-1050-B3IR',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Dead Sea Mud Mask',
##    'search_name' : 'Dead Sea Mud Mask',
##    'sku' : '9D-BZC2-93AO',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Grapefruit Oil',
##    'search_name' : 'Grapefruit Oil',
##    'sku' : '4J-YNLD-KLGK',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'BrownSugarScrub10oz',
##    'search_name' : 'BrownSugarScrub10oz',
##    'sku' : 'BrownSugarScrub10oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'SweetOrangeScrub',
##    'search_name' : 'SweetOrangeScrub',
##    'sku' : 'SweetOrangeScrub',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'ChamomileOil4oz',
##    'search_name' : 'ChamomileOil4oz',
##    'sku' : 'ChamomileOil4oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Myrrh Oil',
##    'search_name' : 'Myrrh Oil',
##    'sku' : 'KO-I58S-WEWY',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Oregano Oil',
##    'search_name' : 'Oregano Oil',
##    'sku' : 'E8-NMQ5-FJ05',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Diffuser 250ml',
##    'search_name' : 'Diffuser 250ml',
##    'sku' : 'AdvanceOilDiffuser',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'CinnamonOil-4flOz',
##    'search_name' : 'CinnamonOil-4flOz',
##    'sku' : 'CinnamonOil-4flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Aloe Vera Combo',
##    'search_name' : 'Aloe Vera Combo',
##    'sku' : 'AloeVeraGel-16floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'CallusRemoverGel',
##    'search_name' : 'CallusRemoverGel',
##    'sku' : 'CallusRemoverGel',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Frankincense4oz',
##    'search_name' : 'Frankincense4oz',
##    'sku' : 'Frankincense4oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'HairGel16flOz',
##    'search_name' : 'HairGel16flOz',
##    'sku' : 'HairGel16flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Clary Sage oil',
##    'search_name' : 'Clary Sage oil',
##    'sku' : '7W-UX75-3750',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'GingerOil4FlOz',
##    'search_name' : 'GingerOil4FlOz',
##    'sku' : 'GingerOil4FlOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'CloveOil-4flOz',
##    'search_name' : 'CloveOil-4flOz',
##    'sku' : 'CloveOil-4flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Juniper Oil',
##    'search_name' : 'Juniper Oil',
##    'sku' : 'G9-CLOG-DZRL',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Diffuser 400ml',
##    'search_name' : 'Diffuser 400ml',
##    'sku' : '500mLdiffuser',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'MatchaGreenTeaScrub',
##    'search_name' : 'MatchaGreenTeaScrub',
##    'sku' : 'MatchaGreenTeaScrub',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'NEWArganSetShampooConditioner',
##    'search_name' : 'NEWArganSetShampooConditioner',
##    'sku' : 'NEWArganSetShampooConditioner',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Tea trea wash seaweed',
##    'search_name' : 'Tea trea wash seaweed',
##    'sku' : 'TeaTreaBodyWash',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'ArabicaScrub10oz',
##    'search_name' : 'ArabicaScrub10oz',
##    'sku' : 'ArabicaScrub10oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'ShampooConditionerTeaTreeSet',
##    'search_name' : 'ShampooConditionerTeaTreeSet',
##    'sku' : 'ShampooConditionerTeaTreeSet',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Drying Lotion',
##    'search_name' : 'Drying Lotion',
##    'sku' : 'P8-ISVD-I4CL',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Bentonite Clay',
##    'search_name' : 'Bentonite Clay',
##    'sku' : 'BX-N0NF-ETC9',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Castor Oil',
##    'search_name' : 'Castor Oil',
##    'sku' : 'LV-XBR2-FJDV',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'ArganConditioner16flOz',
##    'search_name' : 'ArganConditioner16flOz',
##    'sku' : 'ArganConditioner16flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'SandalwoodOil-1flOz',
##    'search_name' : 'SandalwoodOil-1flOz',
##    'sku' : 'SandalwoodOil-1flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'NewGeraniumOil2oz',
##    'search_name' : 'NewGeraniumOil2oz',
##    'sku' : 'NewGeraniumOil2oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'NailPolishRemover4floz',
##    'search_name' : 'NailPolishRemover4floz',
##    'sku' : 'NailPolishRemover4floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Himalayan-Coffee-Scrubs',
##    'search_name' : 'Himalayan-Coffee-Scrubs',
##    'sku' : 'Himalayan-Coffee-Scrubs',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'LotionVitaminC',
##    'search_name' : 'LotionVitaminC',
##    'sku' : 'LotionVitaminC',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Coconut Hair Mask',
##    'search_name' : 'Coconut Hair Mask',
##    'sku' : 'KV-R48F-ZRVY',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'essential oil blends',
##    'search_name' : 'essential oil blends',
##    'sku' : 'FL-PF4H-2VT8',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Rosemary shampoo',
##    'search_name' : 'Rosemary shampoo',
##    'sku' : '97-IG90-MOAA',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Himalayan Salt lamp',
##    'search_name' : 'Himalayan Salt lamp',
##    'sku' : 'B0-XL4G-CGTE',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'TeethWhiteningCharcoal',
##    'search_name' : 'TeethWhiteningCharcoal',
##    'sku' : 'TeethWhiteningCharcoal',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Eyelash Serum 5ml',
##    'search_name' : 'Eyelash Serum 5ml',
##    'sku' : 'EyelashSerum3.5ml',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'AfterShaveBalm-4floz',
##    'search_name' : 'AfterShaveBalm-4floz',
##    'sku' : 'AfterShaveBalm-4floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Jojoba Oil',
##    'search_name' : 'Jojoba Oil',
##    'sku' : 'JB-RO97-9L06',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Black Pepper',
##    'search_name' : 'Black Pepper',
##    'sku' : '48-62AK-XNDW',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'TripleActionEyeCream1FL',
##    'search_name' : 'TripleActionEyeCream1FL',
##    'sku' : 'TripleActionEyeCream1FL',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'VitaminC-Serum 1floz',
##    'search_name' : 'VitaminC-Serum 1floz',
##    'sku' : 'VitaminC-Serum 1floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'ShavingCream-4flOz',
##    'search_name' : 'ShavingCream-4flOz',
##    'sku' : 'ShavingCream-4flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'SuperRetinolSerum1oz',
##    'search_name' : 'SuperRetinolSerum1oz',
##    'sku' : 'SuperRetinolSerum1oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'HairGel-8floz',
##    'search_name' : 'HairGel-8floz',
##    'sku' : 'HairGel-8floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Frankincense Oil',
##    'search_name' : 'Frankincense Oil',
##    'sku' : '1Z-OI9H-EH61',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Shaving Kit',
##    'search_name' : 'Shaving Kit',
##    'sku' : 'GC-BZDF-8KT9',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'BrighteningSerum1FL',
##    'search_name' : 'BrighteningSerum1FL',
##    'sku' : 'BrighteningSerum1FL',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Blue Eye Gel',
##    'search_name' : 'Blue Eye Gel',
##    'sku' : 'H0-S1BK-33MJ',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'RetinalEyeCream-1flOz',
##    'search_name' : 'RetinalEyeCream-1flOz',
##    'sku' : 'RetinalEyeCream-1flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'RetinolCream1oz',
##    'search_name' : 'RetinolCream1oz',
##    'sku' : 'RetinolCream1oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'FacialCleanserCharcoal4flOz',
##    'search_name' : 'FacialCleanserCharcoal4flOz',
##    'sku' : 'FacialCleanserCharcoal4flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'CamelliaCleansingOil-9flOz',
##    'search_name' : 'CamelliaCleansingOil-9flOz',
##    'sku' : 'CamelliaCleansingOil-9flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'SetOf6EssentialOils',
##    'search_name' : 'SetOf6EssentialOils',
##    'sku' : 'SetOf6EssentialOils',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'RosehipCreamCleanser',
##    'search_name' : 'RosehipCreamCleanser',
##    'sku' : 'RosehipCreamCleanser',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'TeaTreeBodyFootScrub',
##    'search_name' : 'TeaTreeBodyFootScrub',
##    'sku' : 'TeaTreeBodyFootScrub',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'DeadSeaMudMaskTTO',
##    'search_name' : 'DeadSeaMudMaskTTO',
##    'sku' : 'DeadSeaMudMaskTTO',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'BathBombs6',
##    'search_name' : 'BathBombs6',
##    'sku' : 'BathBombs6',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Helichrysumoil1oz',
##    'search_name' : 'Helichrysumoil1oz',
##    'sku' : 'Helichrysumoil1oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'ArganOilHairMask Keratin',
##    'search_name' : 'ArganOilHairMask Keratin',
##    'sku' : 'ArganOilHairMask',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'DeadSeaSaltScrub',
##    'search_name' : 'DeadSeaSaltScrub',
##    'sku' : 'DeadSeaSaltScrub',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'LavenderMassageOil',
##    'search_name' : 'LavenderMassageOil',
##    'sku' : 'LavenderMassageOil',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'GoldScrub8.8oz',
##    'search_name' : 'GoldScrub8.8oz',
##    'sku' : 'GoldScrub8.8oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'PeppermitnOilsetof2',
##    'search_name' : 'PeppermitnOilsetof2',
##    'sku' : 'PeppermitnOilsetof2',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'EucalyptusOilsetof2',
##    'search_name' : 'EucalyptusOilsetof2',
##    'sku' : 'EucalyptusOilsetof2',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Frankincense Oil 1 oz',
##    'search_name' : 'Frankincense Oil 1 oz',
##    'sku' : 'P3-ZL9S-XBOQ',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Peppermint Oil 1 oz',
##    'search_name' : 'Peppermint Oil 1 oz',
##    'sku' : 'PM-TF2K-55L6',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'ArganShampoo16flOz',
##    'search_name' : 'ArganShampoo16flOz',
##    'sku' : 'ArganShampoo16flOz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Coconut Body Scrub',
##    'search_name' : 'Coconut Body Scrub',
##    'sku' : '2H-DX31-4SOC',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'HimalayanScrubSet2',
##    'search_name' : 'HimalayanScrubSet2',
##    'sku' : 'HimalayanScrubSet2',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Mango Butter',
##    'search_name' : 'Mango Butter',
##    'sku' : 'U2-CMBQ-5ACI',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Basil Oil',
##    'search_name' : 'Basil Oil',
##    'sku' : 'IQ-AWHQ-F2ST',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Himalayan Salt Block',
##    'search_name' : 'Himalayan Salt Block',
##    'sku' : 'ZL-EJP1-JVQD',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Wintergreen Oil',
##    'search_name' : 'Wintergreen Oil',
##    'sku' : 'HC-ULZC-DP2N',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Clove oil 1 oz',
##    'search_name' : 'Clove oil 1 oz',
##    'sku' : 'ML-I7T0-RMCW',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Argan Hair Mask',
##    'search_name' : 'Argan Hair Mask',
##    'sku' : 'YY-JPC9-1MDT',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'TeaTreeShampoo16floz',
##    'search_name' : 'TeaTreeShampoo16floz',
##    'sku' : 'TeaTreeShampoo16floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Cocoa Butter',
##    'search_name' : 'Cocoa Butter',
##    'sku' : 'Q6-6HM6-A269',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Green Mud Mask',
##    'search_name' : 'Green Mud Mask',
##    'sku' : '4I-JYPH-Y6ET',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Himalayan Salt Block',
##    'search_name' : 'Himalayan Salt Block',
##    'sku' : 'PR-75V4-2U7P',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'BathBombs6',
##    'search_name' : 'BathBombs6',
##    'sku' : 'BathBombs6',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Helichrysum oil',
##    'search_name' : 'Helichrysum oil',
##    'sku' : 'Helichrysumoil1oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'DeadSeaSaltScrub',
##    'search_name' : 'DeadSeaSaltScrub',
##    'sku' : 'DeadSeaSaltScrub',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'LavenderMassageOil',
##    'search_name' : 'LavenderMassageOil',
##    'sku' : 'LavenderMassageOil',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'GoldScrub8.8oz',
##    'search_name' : 'GoldScrub8.8oz',
##    'sku' : 'GoldScrub8.8oz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'EGFScarSerum',
##    'search_name' : 'EGFScarSerum',
##    'sku' : 'EGFScarSerum',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Callus remover 16 oz',
##    'search_name' : 'Callus remover 16 oz',
##    'sku' : 'CallusRemoverTwin',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'TeaTreeShampoo16floz',
##    'search_name' : 'TeaTreeShampoo16floz',
##    'sku' : 'TeaTreeShampoo16floz',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Shea butter shampoo conditioner',
##    'search_name' : 'Shea butter shampoo conditioner',
##    'sku' : 'SheaButterShamppo+Conditioner',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'LavenderCleansingOil',
##    'search_name' : 'LavenderCleansingOil',
##    'sku' : 'LavenderCleansingOil',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Cellulite Body Scrub',
##    'search_name' : 'Cellulite Body Scrub',
##    'sku' : 'CelluliteBodyScrubWLemon',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'Cooling Massage Cream',
##    'search_name' : 'Cooling Massage Cream',
##    'sku' : 'CoolingMuscleCream',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'DSMM with Lavender',
##    'search_name' : 'DSMM with Lavender',
##    'sku' : 'DeadSeaMudMaskLavender',
##    'ad_group_level' : True,
##    },
##    {
##    'identification' : 'GoldScrub8.8oz',
##    'search_name' : 'GoldScrub8.8oz',
##    'sku' : 'TeaTreeShampoo16floz',
##    'ad_group_level' : True,
##    },
##]
